name: Build/release

on: [push, workflow_dispatch]

jobs:
  release:
    runs-on: self-hosted

    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'staging' }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # - name: Create notarization certificate file
      #   run: |
      #     mkdir -p ~/private_keys/
      #     echo '${{ secrets.APPLE_API_KEY }}' > ~/private_keys/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8

      - name: Show all env variables
        run: |
          echo "VITE_MODE: ${VITE_MODE}"
          echo "VITE_API_PATH: ${VITE_API_PATH}"
          echo "VITE_AUTH_APP_URL: ${VITE_AUTH_APP_URL}"
          echo "VITE_LOGIN_IS_REQUIRED: ${VITE_LOGIN_IS_REQUIRED}"
          echo "VITE_PROTOCOL_SCHEME: ${VITE_PROTOCOL_SCHEME}"
          echo "VITE_PRODUCT_NAME: ${VITE_PRODUCT_NAME}"

          echo "MODE: ${MODE}"
          echo "PACKAGE_NAME: ${PACKAGE_NAME}"
          echo "PRODUCT_NAME: ${PRODUCT_NAME}"
          echo "UPDATE_URL: ${UPDATE_URL}"

          echo "CSC_LINK: ${CSC_LINK}"
          echo "CSC_KEY_PASSWORD: ${CSC_KEY_PASSWORD}"
          echo "APPLE_API_KEY: ${APPLE_API_KEY}"
          echo "APPLE_API_KEY_ID: ${APPLE_API_KEY_ID}"
          echo "APPLE_API_ISSUER: ${APPLE_API_ISSUER}"
          echo "APPLE_TEAM_ID: ${APPLE_TEAM_ID}"
          echo "WIN_CSC_LINK: ${WIN_CSC_LINK}"
          echo "WIN_CSC_KEY_PASSWORD: ${WIN_CSC_KEY_PASSWORD}"

      - name: Set package environment meta
        run: |
          echo "npm version"
          npm -v
          echo "Initial package.json version: $(npm pkg get version | tr -d '"')"
          npm pkg set name=${PACKAGE_NAME}
          npm pkg set description=${PRODUCT_NAME}
          [[ ${{ github.ref_name }} != main ]] && npm pkg set version=$(npm pkg get version | tr -d '"')-${{ github.ref_name }}
          echo "New package.json version: $(npm pkg get version | tr -d '"')"

      - name: Build/release Electron app
        uses: Dozorengel/action-electron-builder@v1.7.0
        env:
          VITE_MODE: ${VITE_MODE}
          VITE_API_PATH: ${VITE_API_PATH}
          VITE_AUTH_APP_URL: ${VITE_AUTH_APP_URL}
          VITE_LOGIN_IS_REQUIRED: ${VITE_LOGIN_IS_REQUIRED}
          VITE_PROTOCOL_SCHEME: ${VITE_PROTOCOL_SCHEME}
          VITE_PRODUCT_NAME: ${VITE_PRODUCT_NAME}

          MODE: ${MODE}
          PACKAGE_NAME: ${PACKAGE_NAME}
          PRODUCT_NAME: ${PRODUCT_NAME}
          UPDATE_URL: ${UPDATE_URL}

          CSC_LINK: ${CSC_LINK}
          CSC_KEY_PASSWORD: ${CSC_KEY_PASSWORD}
          APPLE_API_KEY: ${APPLE_API_KEY}
          APPLE_API_KEY_ID: ${APPLE_API_KEY_ID}
          APPLE_API_ISSUER: ${APPLE_API_ISSUER}
          APPLE_TEAM_ID: ${APPLE_TEAM_ID}
          WIN_CSC_LINK: ${WIN_CSC_LINK}
          WIN_CSC_KEY_PASSWORD: ${WIN_CSC_KEY_PASSWORD}
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${GH_TOKEN}
          release: true
          build_script_name: package
          args: --config electron-builder.ts --mac --windows -c.compression=maximum
